export const SET_SOURCE_LANGUAGE = 'SET_SOURCE_LANGUAGE';
export const SET_TARGET_LANGUAGE = 'SET_TARGET_LANGUAGE';
export const SET_SOURCE_TRANSLATIONS = 'SET_SOURCE_TRANSLATIONS';
export const SET_TARGET_TRANSLATIONS = 'SET_TARGET_TRANSLATIONS';
export const SET_RARITY_FILTERS = 'SET_RARITY_FILTERS';
export const SET_RACE_FILTERS = 'SET_RACE_FILTERS';
export const SET_ROLE_FILTERS = 'SET_ROLE_FILTERS';
export const SET_COLOR_FILTERS = 'SET_COLOR_FILTERS';
